### ISSUE TITLE
Exception raised when invoking HAMR

### ISSUE THREAD

**Issue by jdg-11** [sireum/case-env#5] opened 2022-01-06 00:03 UTC
Hi again,

There seems to be an issue with the HAMR code generation engine.  On a fresh vagrant setup or in a manual install on a fresh linux vm, running the HAMR tool from the FMIDE triggers an exception.  This affects both the case-env setup and following the standard notes for installing FMIDE on linux (https://hamr.sireum.org/hamr-doc/ch0X-hamr-installation.html).  

With a simple producer-consumer AADL model loaded in AADL (http://pub.santoslab.org/high-assurance/module-hamr/videos/Tutorial-AADL-Project-from-Scratch.pdf), using the HAMR codegen from the ide produces an exception: java.lang.NoSuchMethodError: ...

Full console output:

```
Sireum Version: 4.20220105.3f63a51 located at /home/vagrant/CASE/Sireum/bin/sireum.jar
Generating System Instance ...
Generating AIR ...
Wrote: /home/vagrant/CASE/Sireum/bin/linux/fmide/workspace/ProdCons/.slang/ProdCons_ProdConsSystem_i_Instance.json
Generating HAMR artifacts...
Exception raised when invoking HAMR
java.lang.NoSuchMethodError: 'org.sireum.Z org.sireum.cli.HAMR.codeGenH(org.sireum.hamr.ir.Aadl, boolean, org.sireum.Cli$SireumHamrCodegenHamrPlatform$Type, org.sireum.Option, org.sireum.Option, boolean, boolean, boolean, org.sireum.IS, org.sireum.Option, boolean, org.sireum.Z, org.sireum.Z, org.sireum.Z, boolean, org.sireum.Option, org.sireum.IS, org.sireum.Option, org.sireum.IS)'
	at org.sireum.aadl.osate.hamr.handlers.LaunchHAMR.lambda$2(LaunchHAMR.java:175)
	at org.sireum.aadl.osate.util.Util.lambda$1(Util.java:90)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withErr(Console.scala:193)
	at scala.Console.withErr(Console.scala)
	at org.sireum.aadl.osate.util.Util.lambda$0(Util.java:87)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withOut(Console.scala:164)
	at scala.Console.withOut(Console.scala)
	at org.sireum.aadl.osate.util.Util.callWrapper(Util.java:86)
	at org.sireum.aadl.osate.hamr.handlers.LaunchHAMR.runJob(LaunchHAMR.java:138)
	at org.sireum.aadl.osate.handlers.AbstractSireumHandler$1.runInWorkspace(AbstractSireumHandler.java:101)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
HAMR code generation was unsuccessful
```

The above is from a run in the vagrant vm.  A similar error exists when the fmide was directly installed in a linux vm:

```
Sireum Version: 4.20220105.3f63a51 located at /home/jdgallag/GitLink/Sireum/bin/sireum.jar
Generating System Instance ...
Generating AIR ...
Wrote: /home/jdgallag/hamrProjects/aadl/.slang/ProdCons_ProdConsSystem_i_Instance.json
Generating HAMR artifacts...
Exception raised when invoking HAMR
java.lang.NoSuchMethodError: 'org.sireum.Z org.sireum.cli.HAMR.codeGenH(org.sireum.hamr.ir.Aadl, boolean, org.sireum.Cli$SireumHamrCodegenHamrPlatform$Type, org.sireum.Option, org.sireum.Option, boolean, boolean, boolean, org.sireum.IS, org.sireum.Option, boolean, org.sireum.Z, org.sireum.Z, org.sireum.Z, boolean, org.sireum.Option, org.sireum.IS, org.sireum.Option, org.sireum.IS)'
	at org.sireum.aadl.osate.hamr.handlers.LaunchHAMR.lambda$2(LaunchHAMR.java:175)
	at org.sireum.aadl.osate.util.Util.lambda$1(Util.java:90)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withErr(Console.scala:193)
	at scala.Console.withErr(Console.scala)
	at org.sireum.aadl.osate.util.Util.lambda$0(Util.java:87)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withOut(Console.scala:164)
	at scala.Console.withOut(Console.scala)
	at org.sireum.aadl.osate.util.Util.callWrapper(Util.java:86)
	at org.sireum.aadl.osate.hamr.handlers.LaunchHAMR.runJob(LaunchHAMR.java:138)
	at org.sireum.aadl.osate.handlers.AbstractSireumHandler$1.runInWorkspace(AbstractSireumHandler.java:101)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
HAMR code generation was unsuccessful
```

Is there any easy fix for this?  Alternatively, the generation of the json file does succeed.  Is there a sequence of command line invocations that could be run that would just use hamr on the json output to trigger the codegen?  

The backend also doesn't seem to matter.  The same error occurs on JVM, linux and sel4 builds.

If there is any other information that would be helpful, let me know, or if there is a way to help fix the problem, feel free to let me know.

**Comment by John-Hatcliff** [comment] 2022-01-06 03:42
Hi,  (Jason, see the issue below, can you take over?  I’ve done as much as I can on the debugging)

Sorry for the problem.
When I worked updating these tutorials in October, the code generation was working, so 
some problem must have been introduced in the code generation pipeline that was not caught by
our regression tests.  

Just to make sure we are on the same page, we are going to debug this issue using
the model at the link below (which is presented on my course web page as the model solution to the AADL From Scratch exercise).

http://pub.santoslab.org/high-assurance/module-hamr/videos/HAMR-Slang-Tutorials-Prod-Cons-AADL-only.zip

I confirmed that running HAMR on the model above gives me the same type of error that you are seeing.

Just curious, were you able to move through the previous exercises without a problem? E.g.,
the Tool Exercise: Refactoring a Slang Implementation of an AADL System (which also requires code generation).

Also one thing to watch out for: The video for the Slang Project from Scratch has some sections that are out of date:
it uses our old SBT build framework instead of the new Projek build framework.  However, the written instructions
for that tutorial should be fine. http://pub.santoslab.org/high-assurance/module-hamr/videos/Tutorial-Slang-Project-from-Scratch.pdf
I had a student that I believe was able to make it through that without any problems.

 — john


[Notes to Jason:

I tried the model from the zip file above using 4.20220105.29d9922 and also what I previously had installed:  4.20211223.c717627
and I had a similar failure on both.   I believe this was going through the tool fine as recently as October because that is 
when I updated the tutorial.]


  





> On Jan 5, 2022, at 6:04 PM, jdg-11 ***@***.***> wrote:
> 
> This email originated from outside of K-State.
> 
> 
> 
> Hi again,
> 
> There seems to be an issue with the HAMR code generation engine. On a fresh vagrant setup or in a manual install on a fresh linux vm, running the HAMR tool from the FMIDE triggers an exception. This affects both the case-env setup and following the standard notes for installing FMIDE on linux (https://hamr.sireum.org/hamr-doc/ch0X-hamr-installation.html).
> 
> With a simple producer-consumer AADL model loaded in AADL (http://pub.santoslab.org/high-assurance/module-hamr/videos/Tutorial-AADL-Project-from-Scratch.pdf), using the HAMR codegen from the ide produces an exception: java.lang.NoSuchMethodError: ...
> 
> Full console output:
> 
> Sireum Version: 4.20220105.3f63a51 located at /home/vagrant/CASE/Sireum/bin/sireum.jar
> Generating System Instance ...
> Generating AIR ...
> Wrote: /home/vagrant/CASE/Sireum/bin/linux/fmide/workspace/ProdCons/.slang/ProdCons_ProdConsSystem_i_Instance.json
> Generating HAMR artifacts...
> Exception raised when invoking HAMR
> java.lang.NoSuchMethodError: 'org.sireum.Z org.sireum.cli.HAMR.codeGenH(org.sireum.hamr.ir.Aadl, boolean, org.sireum.Cli$SireumHamrCodegenHamrPlatform$Type, org.sireum.Option, org.sireum.Option, boolean, boolean, boolean, org.sireum.IS, org.sireum.Option, boolean, org.sireum.Z, org.sireum.Z, org.sireum.Z, boolean, org.sireum.Option, org.sireum.IS, org.sireum.Option, org.sireum.IS)'
> 	at org.sireum.aadl.osate.hamr.handlers.LaunchHAMR.lambda$2(LaunchHAMR.java:175)
> 	at org.sireum.aadl.osate.util.Util.lambda$1(Util.java:90)
> 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
> 	at scala.Console$.withErr(Console.scala:193)
> 	at scala.Console.withErr(Console.scala)
> 	at org.sireum.aadl.osate.util.Util.lambda$0(Util.java:87)
> 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
> 	at scala.Console$.withOut(Console.scala:164)
> 	at scala.Console.withOut(Console.scala)
> 	at org.sireum.aadl.osate.util.Util.callWrapper(Util.java:86)
> 	at org.sireum.aadl.osate.hamr.handlers.LaunchHAMR.runJob(LaunchHAMR.java:138)
> 	at org.sireum.aadl.osate.handlers.AbstractSireumHandler$1.runInWorkspace(AbstractSireumHandler.java:101)
> 	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> HAMR code generation was unsuccessful
> 
> The above is from a run in the vagrant vm. A similar error exists when the fmide was directly installed in a linux vm:
> 
> Sireum Version: 4.20220105.3f63a51 located at /home/jdgallag/GitLink/Sireum/bin/sireum.jar
> Generating System Instance ...
> Generating AIR ...
> Wrote: /home/jdgallag/hamrProjects/aadl/.slang/ProdCons_ProdConsSystem_i_Instance.json
> Generating HAMR artifacts...
> Exception raised when invoking HAMR
> java.lang.NoSuchMethodError: 'org.sireum.Z org.sireum.cli.HAMR.codeGenH(org.sireum.hamr.ir.Aadl, boolean, org.sireum.Cli$SireumHamrCodegenHamrPlatform$Type, org.sireum.Option, org.sireum.Option, boolean, boolean, boolean, org.sireum.IS, org.sireum.Option, boolean, org.sireum.Z, org.sireum.Z, org.sireum.Z, boolean, org.sireum.Option, org.sireum.IS, org.sireum.Option, org.sireum.IS)'
> 	at org.sireum.aadl.osate.hamr.handlers.LaunchHAMR.lambda$2(LaunchHAMR.java:175)
> 	at org.sireum.aadl.osate.util.Util.lambda$1(Util.java:90)
> 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
> 	at scala.Console$.withErr(Console.scala:193)
> 	at scala.Console.withErr(Console.scala)
> 	at org.sireum.aadl.osate.util.Util.lambda$0(Util.java:87)
> 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
> 	at scala.Console$.withOut(Console.scala:164)
> 	at scala.Console.withOut(Console.scala)
> 	at org.sireum.aadl.osate.util.Util.callWrapper(Util.java:86)
> 	at org.sireum.aadl.osate.hamr.handlers.LaunchHAMR.runJob(LaunchHAMR.java:138)
> 	at org.sireum.aadl.osate.handlers.AbstractSireumHandler$1.runInWorkspace(AbstractSireumHandler.java:101)
> 	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> HAMR code generation was unsuccessful
> 
> Is there any easy fix for this? Alternatively, the generation of the json file does succeed. Is there a sequence of command line invocations that could be run that would just use hamr on the json output to trigger the codegen?
> 
> The backend also doesn't seem to matter. The same error occurs on JVM, linux and sel4 builds.
> 
> Is there any other information that would be helpful, let me know, or if there is a way to help fix the problem, feel free to let me know.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you are subscribed to this thread.
> 

-----------------------------------------------------------------------------
Dr. John Hatcliff                    Phone: 785-532-7950 (direct)
University Distinguished Professor   Phone: 785-532-6350 (secretary)
Lucas-Rathbone Professor             Fax..: 785-532-7353
  of Engineering
Computer Science Department          Email: ***@***.***
2160 Engineering Hall                Web: http://people.cis.ksu.edu/~hatcliff
Kansas State University
Manhattan, KS 66506
------------------------------------------------------------------------------

**Comment by jdg-11** [comment] 2022-01-06 16:40
Hi John and Jason,

I have not tried all the previous tutorials in the course, but I did pop into bits of some of them as needed to get the project structure correct etc.  I will check out the `Tool Exercise: Refactoring a Slang Implementation of an AADL System` and see if the code gen works there.  

Let me know if there's anything else I can do that would be useful.

- Jonathan

**Comment by jdg-11** [comment] 2022-01-06 17:58
Update: I tried the suggested `Tool Exercise: Refactoring a Slang Implementation of an AADL System` on both the vagrant setup and standard install on fresh vm and the code gen generates essentially the same exception as before.

    java.lang.NoSuchMethodError: 'org.sireum.Z org.sireum.cli.HAMR.codeGenH( ...

**Comment by jasonbelt** [comment] 2022-01-07 01:44
@jdg-11 

Thanks for reporting this. I had made changes to HAMR codegen’s CLI but didn’t release an updated version of codegen’s OSATE plugin as our CI tests didn’t uncover this issue. 

I just released a new version that resolves this.

You can install the new version by running the following from the command line:

$SIREUM_HOME/bin/install/fmide.cmd

**Comment by jasonbelt** [comment] 2022-01-14 20:39
I'm closing this issue as HAMR codegen completes successfully when run via OSATE using a freshly built case-env VM.

**Closed by jasonbelt** 2022-01-14 20:39 UTC
